sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t littlewhiteloti/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true littlewhiteloti/multi-docker npm test

after_success:
  - docker build -t littlewhiteloti/multi-client ./client
  - docker build -t littlewhiteloti/multi-nginx ./nginx
  - docker build -t littlewhiteloti/multi-server ./server
  - docker build -t littlewhiteloti/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push littlewhiteloti/multi-client:latest
  - docker push littlewhiteloti/multi-nginx:latest
  - docker push littlewhiteloti/multi-server:latest
  - docker push littlewhiteloti/multi-worker:latest